# Generated by Django 3.0.6 on 2020-06-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.Driver')),
            ],
        ),
    ]
