# Generated by Django 3.0.6 on 2020-06-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shopper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shoppers.Shopper'),
            preserve_default=False,
        ),
    ]
